version: "3.8"
services:
  go-server:
    container_name: gcp_scanner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
